on:
  push:
    branches:
      - main
      - staging
      - trying
      - release/**
  pull_request:
  schedule: [cron: "45 6 * * *"]
  workflow_dispatch:

name: Run tests
jobs:
  lints:
    name: Run cargo fmt and cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install fmt & clippy
        run: rustup component add clippy rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo test
        run: cargo test
      - name: Run cargo docs
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
